# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  shellcheck: circleci/shellcheck@2.2.4
# Orchestrate or schedule a set of jobs
workflows:
  check-build:
    jobs:
      - shellcheck/check # job defined within the orb so no further config necessary

